// ============================================================
// Surge Platform - Seed Data
// Austin's actual pipeline + Rehab Restoration's real metrics
// ============================================================

import type {
  Prospect,
  Signal,
  Audit,
  Activity,
  RevenueEvent,
  RetainerClient,
  ClientJob,
  StaffMember,
  ActionItem,
  ClientBusinessMetrics,
} from "./types";

const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString();
const daysFromNow = (d: number) => new Date(now.getTime() + d * 86400000).toISOString();

// ── Austin's Prospect Pipeline ──────────────────────────────

export const seedProspects: Prospect[] = [
  {
    id: "p-southern-insurance",
    companyName: "Southern Insurance Group",
    contactName: "David Ashton",
    title: "Owner",
    email: "david@southerninsurance.com",
    phone: "",
    linkedIn: "",
    trade: "other",
    annualRevenue: 2500000,
    employeeCount: 18,
    city: "Atlanta",
    state: "GA",
    tier: 1,
    icpScore: 22,
    stage: "discovery_done",
    spinStage: "payoff",
    triggerEvent: "cold",
    triggerEventDate: daysAgo(14),
    triggerEventSummary: "Inbound warm contact - wants AI workflows + knowledge base",
    referralSource: "Cold inbound",
    lastTouch: daysAgo(3),
    nextTouch: daysFromNow(2),
    touchCount: 4,
    estimatedValue: 40000,
    notes: "$2.5M insurance agency, 14 producers, quoting bottleneck. Wants 10x growth. Needs audit scoped to insurance context.",
    createdAt: daysAgo(14),
    updatedAt: daysAgo(3),
  },
  {
    id: "p-servpro-denver",
    companyName: "ServPro of Northwest Denver",
    contactName: "Mark Jennings",
    title: "Owner",
    email: "",
    phone: "",
    linkedIn: "",
    trade: "restoration",
    annualRevenue: 4500000,
    employeeCount: 22,
    city: "Denver",
    state: "CO",
    tier: 1,
    icpScore: 26,
    stage: "unreached",
    spinStage: "none",
    triggerEvent: "hiring",
    triggerEventDate: daysAgo(2),
    triggerEventSummary: "Posted on Indeed: 'Claims Operations Coordinator' - $50-65k range",
    referralSource: "",
    lastTouch: "",
    nextTouch: daysFromNow(0),
    touchCount: 0,
    estimatedValue: 50000,
    notes: "Hiring signal is fresh. Respond within 48 hours. Likely Jared network overlap.",
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
  },
  {
    id: "p-puroclean-phoenix",
    companyName: "PuroClean of North Phoenix",
    contactName: "Tim Warner",
    title: "Franchise Owner",
    email: "",
    phone: "",
    linkedIn: "",
    trade: "restoration",
    annualRevenue: 3200000,
    employeeCount: 14,
    city: "Phoenix",
    state: "AZ",
    tier: 1,
    icpScore: 24,
    stage: "touched",
    spinStage: "none",
    triggerEvent: "review",
    triggerEventDate: daysAgo(7),
    triggerEventSummary: "Negative Google review complaining about 6-week billing delay on water damage claim",
    referralSource: "",
    lastTouch: daysAgo(4),
    nextTouch: daysFromNow(0),
    touchCount: 1,
    estimatedValue: 45000,
    notes: "Touch 1 sent 4 days ago - no reply yet. Touch 2 (social proof) due today. Phoenix = Austin's home market.",
    createdAt: daysAgo(7),
    updatedAt: daysAgo(4),
  },
  {
    id: "p-belfor-dallas",
    companyName: "BELFOR Dallas",
    contactName: "Rachel Martinez",
    title: "Operations Director",
    email: "",
    phone: "",
    linkedIn: "",
    trade: "restoration",
    annualRevenue: 15000000,
    employeeCount: 95,
    city: "Dallas",
    state: "TX",
    tier: 2,
    icpScore: 18,
    stage: "unreached",
    spinStage: "none",
    triggerEvent: "leadership",
    triggerEventDate: daysAgo(5),
    triggerEventSummary: "Rachel started as new Ops Director - 90-day blank-slate window open",
    referralSource: "",
    lastTouch: "",
    nextTouch: daysFromNow(1),
    touchCount: 0,
    estimatedValue: 90000,
    notes: "Enterprise tier. Longer cycle. Focus is on new leadership first-90-day play.",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: "p-jareds-referral-1",
    companyName: "Mountain West Restoration",
    contactName: "Derek Holloway",
    title: "Owner",
    email: "",
    phone: "",
    linkedIn: "",
    trade: "restoration",
    annualRevenue: 1800000,
    employeeCount: 9,
    city: "Colorado Springs",
    state: "CO",
    tier: 1,
    icpScore: 27,
    stage: "meeting_booked",
    spinStage: "situation",
    triggerEvent: "referral",
    triggerEventDate: daysAgo(3),
    triggerEventSummary: "Jared at Rehab introduced via email - Derek asked for a 15-min call",
    referralSource: "Jared Watts (Rehab Restoration)",
    lastTouch: daysAgo(2),
    nextTouch: daysFromNow(3),
    touchCount: 2,
    estimatedValue: 42000,
    notes: "Discovery call scheduled Thursday. Derek already said 'we have the same problem' when Jared described Rehab's audit findings. Pre-qualified.",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(2),
  },
  {
    id: "p-crawford-florida",
    companyName: "Coastal Claims Restoration",
    contactName: "Angela Morris",
    title: "President",
    email: "",
    phone: "",
    linkedIn: "",
    trade: "restoration",
    annualRevenue: 7500000,
    employeeCount: 38,
    city: "Tampa",
    state: "FL",
    tier: 1,
    icpScore: 25,
    stage: "responding",
    spinStage: "situation",
    triggerEvent: "expansion",
    triggerEventDate: daysAgo(11),
    triggerEventSummary: "Announced new Jacksonville branch opening Q3 - ops infrastructure greenfield opportunity",
    referralSource: "",
    lastTouch: daysAgo(1),
    nextTouch: daysFromNow(2),
    touchCount: 3,
    estimatedValue: 55000,
    notes: "Replied to Touch 2 with 'interested but busy.' High-probability tier 1 - hurricane market means seasonal urgency.",
    createdAt: daysAgo(11),
    updatedAt: daysAgo(1),
  },
];

// ── Active Signals (Recent Trigger Events) ──────────────────

export const seedSignals: Signal[] = [
  {
    id: "s-1",
    type: "hiring",
    source: "indeed",
    companyName: "ServPro of Northwest Denver",
    contactName: "Mark Jennings",
    summary: "Posted 'Claims Operations Coordinator' role - $50-65k range. Hiring = investing in ops function.",
    url: "https://indeed.com/...",
    detectedAt: daysAgo(2),
    prospectId: "p-servpro-denver",
    status: "new",
    actionTaken: "",
  },
  {
    id: "s-2",
    type: "expansion",
    source: "linkedin",
    companyName: "Rocky Mountain Restoration",
    contactName: "Ben Carter",
    summary: "LinkedIn post announcing opening of Fort Collins branch in May. Greenfield ops setup opportunity.",
    url: "https://linkedin.com/...",
    detectedAt: daysAgo(1),
    prospectId: null,
    status: "new",
    actionTaken: "",
  },
  {
    id: "s-3",
    type: "review",
    source: "reviews",
    companyName: "All Clean Restoration",
    contactName: "",
    summary: "Google review: 'Waited 3 months for billing to finalize. Still don't have a final answer from them.'",
    url: "https://google.com/...",
    detectedAt: daysAgo(3),
    prospectId: null,
    status: "new",
    actionTaken: "",
  },
  {
    id: "s-4",
    type: "leadership",
    source: "linkedin",
    companyName: "BELFOR Dallas",
    contactName: "Rachel Martinez",
    summary: "Rachel Martinez announced as new Operations Director at BELFOR Dallas - 2 days ago.",
    url: "https://linkedin.com/...",
    detectedAt: daysAgo(5),
    prospectId: "p-belfor-dallas",
    status: "reviewed",
    actionTaken: "Added to Tier 2 queue. Touch 1 scheduled for tomorrow morning.",
  },
  {
    id: "s-5",
    type: "referral",
    source: "referral",
    companyName: "Mountain West Restoration",
    contactName: "Derek Holloway",
    summary: "Jared Watts (Rehab Restoration) made warm intro via email. Derek asked for 15-min call.",
    url: "",
    detectedAt: daysAgo(3),
    prospectId: "p-jareds-referral-1",
    status: "actioned",
    actionTaken: "Discovery call booked Thursday 2pm MT. Pre-qualified via Jared.",
  },
  {
    id: "s-6",
    type: "hiring",
    source: "indeed",
    companyName: "Servpro of Southeast Denver",
    contactName: "",
    summary: "Posted 'Restoration Project Manager' role. Another Denver-area ops hire.",
    url: "https://indeed.com/...",
    detectedAt: daysAgo(1),
    prospectId: null,
    status: "new",
    actionTaken: "",
  },
];

// ── Audits (Active + Historical) ────────────────────────────

export const seedAudits: Audit[] = [
  {
    id: "a-rehab",
    prospectId: "p-rehab-original",
    clientId: "rehab-restoration",
    companyName: "Rehab Restoration",
    startDate: daysAgo(22),
    targetDeliveryDate: daysAgo(8),
    stage: "converted_to_retainer",
    paymentAmount: 3500,
    apiAccessGranted: true,
    findings: {
      stuckRevenue: 1300000,
      blockedJobs: 393,
      dataIntegrityScore: 12,
      recommendedPath: "B",
      projectedROI: 713000,
    },
    outcomes: {
      retainerConverted: true,
      retainerPhase: 1,
      creditApplied: true,
    },
    createdAt: daysAgo(22),
  },
];

// ── Activities ──────────────────────────────────────────────

export const seedActivities: Activity[] = [
  {
    id: "ac-1",
    prospectId: "p-jareds-referral-1",
    clientId: null,
    type: "email_received",
    direction: "inbound",
    subject: "Re: Austin at Surge - worth 15 minutes",
    summary: "Derek replied: 'Jared told me about the audit you did on their business. We have the same collections issue. Can we talk Thursday afternoon?'",
    recordingUrl: "",
    sentiment: "positive",
    spinStageReached: "none",
    nextStepIdentified: "Book discovery call Thursday 2pm MT",
    nextStepDate: daysFromNow(3),
    createdAt: daysAgo(2),
  },
  {
    id: "ac-2",
    prospectId: "p-southern-insurance",
    clientId: null,
    type: "call",
    direction: "outbound",
    subject: "Discovery call with David Ashton",
    summary: "45-min call. David confirmed quoting bottleneck, 14 producers doing manual entry. Implication questions hit - he calculated $180K/yr lost capacity. Ready to move on audit.",
    recordingUrl: "https://fireflies.ai/...",
    sentiment: "positive",
    spinStageReached: "payoff",
    nextStepIdentified: "Send audit proposal + contract",
    nextStepDate: daysFromNow(2),
    createdAt: daysAgo(3),
  },
  {
    id: "ac-3",
    prospectId: "p-puroclean-phoenix",
    clientId: null,
    type: "email_sent",
    direction: "outbound",
    subject: "Saw the review from Margaret",
    summary: "Touch 1 sent referencing specific negative review about billing delay. No reply yet.",
    recordingUrl: "",
    sentiment: "neutral",
    spinStageReached: "none",
    nextStepIdentified: "Touch 2 social proof email",
    nextStepDate: daysFromNow(0),
    createdAt: daysAgo(4),
  },
];

// ── Revenue Events ──────────────────────────────────────────

export const seedRevenueEvents: RevenueEvent[] = [
  {
    id: "r-1",
    type: "audit_payment",
    amount: 3500,
    clientId: "rehab-restoration",
    prospectId: "p-rehab-original",
    description: "Rehab Restoration - Ops Audit payment",
    date: daysAgo(22),
  },
  {
    id: "r-2",
    type: "retainer_payment",
    amount: 6500,
    clientId: "rehab-restoration",
    prospectId: null,
    description: "Rehab Restoration - April Phase 1 retainer (credited $3,500 from audit = $3,000 net)",
    date: daysAgo(14),
  },
  {
    id: "r-3",
    type: "retainer_payment",
    amount: 970.10,
    clientId: "rehab-restoration",
    prospectId: null,
    description: "Rehab Restoration - first payment received (Intuit ACH)",
    date: daysAgo(2),
  },
];

// ── Retainer Clients ────────────────────────────────────────

export const seedRetainerClients: RetainerClient[] = [
  {
    id: "rehab-restoration",
    companyName: "Rehab Restoration",
    contactName: "Scott Wahrer",
    phase: 1,
    phaseStartDate: daysAgo(14),
    monthlyRetainer: 6500,
    healthScore: 78,
    lastCheckIn: daysAgo(0),
    nextCheckIn: daysFromNow(7),
    keyChampion: "Jared Watts",
    notes: "Claude 101 training with Zoie + Silvia on April 23. Ops infrastructure recommendation doc delivered. Awaiting Scott + Aaron path decision (A/B/C).",
  },
];

// ── Rehab Restoration: Client Platform Data ─────────────────

export const seedClientJobs: ClientJob[] = [
  {
    id: "j-1",
    clientId: "rehab-restoration",
    externalJobId: "JN-4821",
    customerName: "James Wilson",
    address: "2847 Pine Ridge Dr, Colorado Springs CO",
    jobType: "water",
    carrier: "State Farm",
    adjusterName: "Tom Reynolds",
    adjusterEmail: "t.reynolds@statefarm.com",
    stage: "collections",
    amount: 86574,
    daysInCurrentStage: 3,
    daysFromFNOL: 87,
    flags: ["recently_entered_5_0", "large_exposure"],
    lastActivity: daysAgo(3),
    assignedTech: "Aaron",
    assignedAdmin: "Zoie",
    notes: "Just entered 5.0. Highest-dollar at-risk job. Priority in new collection sequence.",
  },
  {
    id: "j-2",
    clientId: "rehab-restoration",
    externalJobId: "JN-3492",
    customerName: "Amy Forde",
    address: "1204 Willowbrook Ln, Pueblo CO",
    jobType: "water",
    carrier: "Allstate",
    adjusterName: "Janet Hill",
    adjusterEmail: "",
    stage: "collections",
    amount: 34848,
    daysInCurrentStage: 576,
    daysFromFNOL: 612,
    flags: ["extreme_age", "adjuster_nonresponsive_120d"],
    lastActivity: daysAgo(120),
    assignedTech: "Unknown",
    assignedAdmin: "Tammy",
    notes: "Worst-case aging. 576 days stuck. Likely partially uncollectable but still worth 20% recovery attempt.",
  },
  {
    id: "j-3",
    clientId: "rehab-restoration",
    externalJobId: "JN-5102",
    customerName: "Robert Chen",
    address: "55 Mountain View Rd, Denver CO",
    jobType: "fire",
    carrier: "USAA",
    adjusterName: "Derek Patterson",
    adjusterEmail: "d.patterson@usaa.com",
    stage: "mitigation",
    amount: 42300,
    daysInCurrentStage: 8,
    daysFromFNOL: 12,
    flags: ["missing_moisture_log", "missing_soot_photos"],
    lastActivity: daysAgo(1),
    assignedTech: "Jared",
    assignedAdmin: "Silvia",
    notes: "Documentation gap detected. Tech alerted via SMS at 3.3 approach.",
  },
  {
    id: "j-4",
    clientId: "rehab-restoration",
    externalJobId: "JN-5134",
    customerName: "Lisa Peterson",
    address: "789 Aspen Ave, Boulder CO",
    jobType: "water",
    carrier: "Liberty Mutual",
    adjusterName: "Marcus Wells",
    adjusterEmail: "m.wells@libertymutual.com",
    stage: "rebuild",
    amount: 28500,
    daysInCurrentStage: 14,
    daysFromFNOL: 32,
    flags: [],
    lastActivity: daysAgo(2),
    assignedTech: "Jared",
    assignedAdmin: "Zoie",
    notes: "On track. No blockers.",
  },
];

export const seedStaff: StaffMember[] = [
  {
    id: "st-scott",
    clientId: "rehab-restoration",
    name: "Scott Wahrer",
    role: "owner",
    email: "scott@rehabrestoration.com",
    kpis: {
      jobsHandled: 0,
      docsCompleted: 0,
      supplementsApproved: 0,
      reviewsGenerated: 0,
      collectionsFollowedUp: 0,
      avgResponseTimeHours: 0,
    },
    trainingProgress: {
      coursesCompleted: [],
      certificationsEarned: [],
      currentCourse: null,
    },
    scorecardThisWeek: 0,
    scorecardTrend: "flat",
  },
  {
    id: "st-jared",
    clientId: "rehab-restoration",
    name: "Jared Watts",
    role: "ops_manager",
    email: "jared@rehabrestoration.com",
    kpis: {
      jobsHandled: 18,
      docsCompleted: 32,
      supplementsApproved: 9,
      reviewsGenerated: 4,
      collectionsFollowedUp: 12,
      avgResponseTimeHours: 2.4,
    },
    trainingProgress: {
      coursesCompleted: ["Claim Documentation Fundamentals", "Supplement Win Rate"],
      certificationsEarned: ["Surge Ops Certified"],
      currentCourse: "Adjuster Communication Mastery",
    },
    scorecardThisWeek: 92,
    scorecardTrend: "up",
  },
  {
    id: "st-zoie",
    clientId: "rehab-restoration",
    name: "Zoie Rodrigues",
    role: "admin",
    email: "zoie@rehabrestoration.com",
    kpis: {
      jobsHandled: 24,
      docsCompleted: 41,
      supplementsApproved: 0,
      reviewsGenerated: 8,
      collectionsFollowedUp: 22,
      avgResponseTimeHours: 3.1,
    },
    trainingProgress: {
      coursesCompleted: ["Claude 101 for Admin"],
      certificationsEarned: [],
      currentCourse: "Collection Follow-Up Excellence",
    },
    scorecardThisWeek: 88,
    scorecardTrend: "up",
  },
  {
    id: "st-silvia",
    clientId: "rehab-restoration",
    name: "Silvia Romleski",
    role: "admin",
    email: "silvia@rehabrestoration.com",
    kpis: {
      jobsHandled: 31,
      docsCompleted: 28,
      supplementsApproved: 0,
      reviewsGenerated: 5,
      collectionsFollowedUp: 6,
      avgResponseTimeHours: 4.2,
    },
    trainingProgress: {
      coursesCompleted: ["Claude 101 for Admin"],
      certificationsEarned: [],
      currentCourse: "WhatsApp-to-CRM Workflow Optimization",
    },
    scorecardThisWeek: 82,
    scorecardTrend: "up",
  },
  {
    id: "st-tammy",
    clientId: "rehab-restoration",
    name: "Tammy Chen",
    role: "admin",
    email: "tammy@rehabrestoration.com",
    kpis: {
      jobsHandled: 14,
      docsCompleted: 19,
      supplementsApproved: 0,
      reviewsGenerated: 2,
      collectionsFollowedUp: 18,
      avgResponseTimeHours: 5.8,
    },
    trainingProgress: {
      coursesCompleted: [],
      certificationsEarned: [],
      currentCourse: "Surge Basics",
    },
    scorecardThisWeek: 71,
    scorecardTrend: "flat",
  },
];

export const seedActionItems: ActionItem[] = [
  {
    id: "ai-1",
    clientId: "rehab-restoration",
    assignedToStaffId: "st-jared",
    type: "call_adjuster",
    priority: "urgent",
    title: "Call Tom Reynolds at State Farm on James Wilson job",
    description: "Job JN-4821 just entered 5.0 status at $86,574. First collection SMS sent. No response in 72 hours. Direct adjuster call needed.",
    dollarImpact: 86574,
    dueDate: daysFromNow(0),
    completedAt: null,
    sourceJobId: "j-1",
    generatedBy: "surge_automation",
  },
  {
    id: "ai-2",
    clientId: "rehab-restoration",
    assignedToStaffId: "st-silvia",
    type: "upload_docs",
    priority: "high",
    title: "Upload moisture log + soot photos for Robert Chen",
    description: "Job JN-5102 approaching 3.3 billing stage with documentation gaps. Upload within 48 hours to avoid billing delay.",
    dollarImpact: 42300,
    dueDate: daysFromNow(1),
    completedAt: null,
    sourceJobId: "j-3",
    generatedBy: "surge_automation",
  },
  {
    id: "ai-3",
    clientId: "rehab-restoration",
    assignedToStaffId: "st-zoie",
    type: "follow_up_invoice",
    priority: "high",
    title: "Review 12 invoices hitting 45-day follow-up mark today",
    description: "Automated sequence queued 12 SMS follow-ups. Review before they send and flag any exceptions.",
    dollarImpact: 178000,
    dueDate: daysFromNow(0),
    completedAt: null,
    sourceJobId: null,
    generatedBy: "surge_automation",
  },
  {
    id: "ai-4",
    clientId: "rehab-restoration",
    assignedToStaffId: "st-jared",
    type: "supplement_prep",
    priority: "medium",
    title: "Prepare supplement package for Lisa Peterson rebuild",
    description: "Additional scope identified during rebuild phase. Documentation ready. Package to Marcus Wells at Liberty Mutual.",
    dollarImpact: 8400,
    dueDate: daysFromNow(2),
    completedAt: null,
    sourceJobId: "j-4",
    generatedBy: "manual",
  },
  {
    id: "ai-5",
    clientId: "rehab-restoration",
    assignedToStaffId: "st-tammy",
    type: "response_review",
    priority: "medium",
    title: "Respond to 3 new Google reviews",
    description: "3 new reviews posted this week. All 5-star. Response template suggested by platform.",
    dollarImpact: 0,
    dueDate: daysFromNow(1),
    completedAt: null,
    sourceJobId: null,
    generatedBy: "surge_automation",
  },
];

export const seedClientMetrics: ClientBusinessMetrics[] = [
  {
    clientId: "rehab-restoration",
    asOfDate: new Date().toISOString(),
    collections: {
      totalStuck: 1247500, // slightly below $1.3M - some recovered since Surge started
      jobsStuck: 281,
      avgDaysAged: 192,
      recoveredThisMonth: 47500,
      recoveredYTD: 47500,
    },
    pipeline: {
      activeJobs: 109,
      pipelineValue: 1059424,
      blockedAtBilling: 18, // down from 393 - documentation automation kicking in
      documentationGapScore: 68, // up from ~12
    },
    team: {
      memberCount: 5,
      activeToday: 4,
      avgScorecardThisWeek: 83,
    },
    streaks: {
      daysWithCleanFollowUps: 9,
      weeksWith100Compliance: 0,
      daysAllFocusItemsDone: 4,
    },
  },
];

// ── Seed Integrations (Phase 3) ────────────────────────────

import type {
  IntegrationConnection,
  EncircleSessionData,
  AutomationRunLog,
  WeeklyReport,
  ProspectAutomationSuggestion,
  ProspectAutomationRunLog,
  EmailDigest,
  ScheduleConfig,
} from "./types";
import { mockSyncFromEncircle } from "./integrations/encircle";

export const seedIntegrations: IntegrationConnection[] = [
  {
    id: "conn-jobnimbus-rehab",
    clientId: "rehab-restoration",
    provider: "jobnimbus",
    status: "connected",
    lastSyncedAt: daysAgo(0),
    lastSyncSummary: "Synced 109 active jobs, 4 new since yesterday",
    apiKeyMask: "ai-b...rXyz",
    connectedAt: daysAgo(21),
  },
  {
    id: "conn-encircle-rehab",
    clientId: "rehab-restoration",
    provider: "encircle",
    status: "not_connected",
    lastSyncedAt: null,
    lastSyncSummary: "Not connected yet - awaiting Scott's decision on Path B (Albi + Encircle)",
    apiKeyMask: "",
    connectedAt: null,
  },
];

export const seedEncircleSessions: EncircleSessionData[] = mockSyncFromEncircle(seedClientJobs);

export const seedAutomationRuns: AutomationRunLog[] = [];
export const seedWeeklyReports: WeeklyReport[] = [];

// ── Default Empty Store ─────────────────────────────────────

export const emptyStore = {
  prospects: [] as Prospect[],
  signals: [] as Signal[],
  audits: [] as Audit[],
  activities: [] as Activity[],
  revenueEvents: [] as RevenueEvent[],
  retainerClients: [] as RetainerClient[],
  jobs: [] as ClientJob[],
  staff: [] as StaffMember[],
  actionItems: [] as ActionItem[],
  metrics: [] as ClientBusinessMetrics[],
  integrations: [] as IntegrationConnection[],
  encircleSessions: [] as EncircleSessionData[],
  automationRuns: [] as AutomationRunLog[],
  weeklyReports: [] as WeeklyReport[],
  prospectAutomationSuggestions: [] as ProspectAutomationSuggestion[],
  prospectAutomationRuns: [] as ProspectAutomationRunLog[],
  emailDigests: [] as EmailDigest[],
  schedules: [] as ScheduleConfig[],
  initialized: false,
};
